name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: sudharshan-gitH/devops-central-pipeline/.github/workflows/deploy.yaml@main
    with:
      aws-region: us-east-1
      ecr-repo: demo-observability-api
      helm-repo: demo-observability-helm
      eks-cluster: demo-cluster 
    secrets:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_EKS_SECRET: ${{ secrets.AWS_EKS_SECRET }}
       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}


